### ISSUE TITLE
Write documentation for the API

### ISSUE THREAD

**Issue by sameerkumar18** [sameerkumar18/geek-joke-api#1]
It'll be great if someone could write the documentation for the API.
I wrote docs for an API previously, for reference -  https://github.com/sameerkumar18/aztro/blob/master/docs/source/index.rst

**Comment by prydt** [comment]
I'll see what I can do

**Comment by sameerkumar18** [comment]
Sure! @PryDt

**Comment by prydt** [comment]
Is there an API URL being hosted somewhere (that I could use for examples) ? (if not, I will just use something like "http://<api-url>/api" @sameerkumar18

**Comment by ashishpahwa7** [comment]
@sameerkumar18  I don't think documentation required.

**Comment by srijitcoder** [comment]
@ashishpahwa7  I think approach is enough for this project

**Comment by sameerkumar18** [comment]
@PryDt You can use this https://geek-jokes.herokuapp.com/

**Comment by srijitcoder** [comment]
@ashishpahwa7 I think approach is enough for this project.

**Comment by prydt** [comment]
#18
