### ISSUE TITLE
Improve code

### ISSUE THREAD

**Issue by sameerkumar18** [sameerkumar18/geek-joke-api#3]
I wrote this code about 4 months ago when I was trying to implement REST in Flask API.
I think the code can be improved a lot.

**Comment by esouthren** [comment]
I'll have a bash at this

[Pull Request](https://github.com/sameerkumar18/geek-joke-api/pull/19)

**Comment by srijitcoder** [comment]
@sameerkumar18 I can work on this

**Comment by brunoerg** [comment]
I'll help you!

**Comment by aspittel** [comment]
See https://github.com/sameerkumar18/geek-joke-api/pull/14!

**Comment by earvingemenez** [comment]
I opened a PR for this https://github.com/sameerkumar18/geek-joke-api/pull/28

**Comment by Nitish18** [comment]
Hi sameer,
take a look at this PR #31
