### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by b-mi** [sameerkumar18/geek-joke-api#46]
Failed to load https://geek-jokes.sameerkumar.website/api: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

---
Angular 6
HttpClient
default HttpGet
Other api-s work

**Comment by sameerkumar18** [comment]
Can you try again? Did some modifications allowing CORS...

**Comment by b-mi** [comment]
It work now. 
Another issue, there are too many jokes about Chuck Norris.

**Comment by sameerkumar18** [comment]
Known! Feel free to add new jokes :)
